services:
  # Backend
  - type: web
    name: avanthi-backend
    env: docker
    rootDir: MyCampusSmartDashboardSystem
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false # You will paste your MongoDB URL in the Render dashboard
