services:
  # Backend
  - type: web
    name: avanthi-backend
    env: java
    rootDir: MyCampusSmartDashboardSystem
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false # You will paste your MongoDB URL in the Render dashboard
